CREATE TABLE [dbo].[SANPHAM] (
    [MASANPHAM]  NVARCHAR (50) NOT NULL,
    [TENSANPHAM] NVARCHAR (50) NULL,
    [MOTA]       NVARCHAR (50) NULL,
    [GIA]        INT           NULL,
    [HINHANH]    IMAGE NULL,
    [MALOAI]     NVARCHAR (50) NULL,
    [SOLUONG]    INT           NULL,
    PRIMARY KEY CLUSTERED ([MASANPHAM] ASC),
    CONSTRAINT [FK_SANPHAM_ToLOAIDODUNG] FOREIGN KEY ([MALOAI]) REFERENCES [dbo].[LOAIDODUNG] ([MALOAI])
);

